### ISSUE TITLE
Implement command to extract all files, preserving paths

### ISSUE THREAD

**Issue by lubosz** [Kanma/MPQExtractor#12]
As far as I understand there is no command to extract all files in a MPQ archive, including paths.
Isn't this the most obvious thing for this tool to do?
Besides that, great tool, thanks for writing it.

**Comment by Kanma** [comment]
This should work:

`./MPQExtractor -e "*" -f -o out /path/to/art.MPQ`

(note that the * is enclosed in "", to prevent the shell to interpret it)

**Comment by falzard** [comment]
Add it to the readme please :P
