### ISSUE TITLE
Can't extract nor list files

### ISSUE THREAD

**Issue by Maxiglider** [Kanma/MPQExtractor#18]
Hello,

This seems to be a cool tool, but after installing it, when I try to use it it doesn't work.
The output says "Opening '<filename>'...  and stops there.

The files I am trying to extract are w3m and w3x files, maps from Warcraft III. (not necessary Reforged)
I tried with ubuntu 18 and 20.

Thanks if you can help !

**Comment by Kanma** [comment]
Hello

I don't have Warcraft III installed here, so I can't try it right now. But we can try to find the problem.

What command did you enter?

**Comment by Maxiglider** [comment]
Hello,

Thank you for your reply.

`root@max-dedie:~/wc3# MPQExtractor/build/bin/MPQExtractor -o out "MaxEscapeCreation v1.3b.w3x"
Opening 'MaxEscapeCreation v1.3b.w3x'...
root@max-dedie:~/wc3#`
