### ISSUE TITLE
There's no releases

### ISSUE THREAD

**Issue by grepwood** [Kanma/MPQExtractor#22]
Hi, I'm looking at maybe packaging this if it can extract MPQ files from Warcraft 3, since I'm trying to fix a package that used to automate GDI responses in order to wrap the installation of Warcraft 3 in a script.

But without releases, I'll basically have to improvise on the version. Please make a release.

**Comment by Kanma** [comment]
Here you go: https://github.com/Kanma/MPQExtractor/releases/tag/v202405

**Comment by grepwood** [comment]
Thank you very much! :)
