### ISSUE TITLE
Hashes instead of minimap names

### ISSUE THREAD

**Issue by freekode** [Kanma/MPQExtractor#9]
I did try to extract map images from the first version of WoW (1.12.1). But instead of clear title of files I have just hashes (338cbccd624193b9ef38100a0bf806d3.blp and so on). I found some listfiles, but they did not help.
Is it possible transform this hash-names to clear names like map_45_56.blp?

Or may be need another listifle.

**Comment by Kanma** [comment]
Sadly, I have no experience with the MPQs of an old version like that...

You might want to ask for advice on the [StormLib library](https://github.com/ladislav-zezula/StormLib) repository (MPQExtractor is just a small tool on top of that library).

My guess is that it is not possible to convert a hash back to a file name, but it should be possible to hash the file names from a listfile.
